version: '3'
services:
  kkemu:
    image: kktech/kkemu:latest
    build:
      context: '../../'
      dockerfile: 'scripts/emulator/Dockerfile'
    networks:
      - local-net
    ports:
      - "21324:21324/udp"
      - "21325:21325/udp"
  python-keepkey:
    build:
      context: '../../'
      dockerfile: 'scripts/emulator/python-keepkey.Dockerfile'
    volumes:
      - test-reports:/kkemu/test-reports:rw
    networks:
      - local-net
    depends_on:
      - kkemu
  firmware-unit:
    build:
      context: '../../'
      dockerfile: 'scripts/emulator/Dockerfile'
    volumes:
      - test-reports:/kkemu/test-reports:rw
    entrypoint: ['scripts/emulator/firmware-unit.sh']
    networks:
      - local-net
    depends_on:
      - kkemu
networks:
  local-net:
    external: false
volumes:
  test-reports:
    external: false
